CREATE TABLE `chapter_fact_extraction_runs` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `project_id` BIGINT UNSIGNED NOT NULL,
  `chapter_id` BIGINT UNSIGNED NOT NULL,
  `source_content_version_id` BIGINT UNSIGNED NULL,
  `model_config_id` BIGINT UNSIGNED NULL,
  `status` VARCHAR(16) NOT NULL DEFAULT 'success',
  `raw_output_json` LONGTEXT NULL,
  `normalized_output_json` LONGTEXT NOT NULL,
  `issues_json` LONGTEXT NULL,
  `generation_job_id` BIGINT UNSIGNED NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_fact_extraction_project_chapter` (`project_id`, `chapter_id`, `created_at`),
  KEY `idx_fact_extraction_source_version` (`source_content_version_id`),
  KEY `idx_fact_extraction_model_config` (`model_config_id`),
  KEY `idx_fact_extraction_generation_job` (`generation_job_id`),
  CONSTRAINT `fk_fact_extraction_project` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_fact_extraction_chapter` FOREIGN KEY (`chapter_id`) REFERENCES `chapters` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_fact_extraction_source_version` FOREIGN KEY (`source_content_version_id`) REFERENCES `content_versions` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_fact_extraction_model_config` FOREIGN KEY (`model_config_id`) REFERENCES `model_configs` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_fact_extraction_generation_job` FOREIGN KEY (`generation_job_id`) REFERENCES `generation_jobs` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Chapter fact extraction audit runs';

CREATE TABLE `story_dirty_marks` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `project_id` BIGINT UNSIGNED NOT NULL,
  `source_type` VARCHAR(32) NOT NULL,
  `source_id` BIGINT UNSIGNED NOT NULL,
  `source_chapter_id` BIGINT UNSIGNED NULL,
  `source_chapter_no` INT NULL,
  `dirty_from_chapter_no` INT NOT NULL,
  `dirty_scope` VARCHAR(32) NOT NULL DEFAULT 'chapter_postprocess',
  `reason_type` VARCHAR(32) NOT NULL DEFAULT 'chapter_content_changed',
  `reason_note` LONGTEXT NULL,
  `status` VARCHAR(16) NOT NULL DEFAULT 'active',
  `resolved_at` DATETIME NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_story_dirty_marks_project_status` (`project_id`, `status`, `dirty_from_chapter_no`),
  KEY `idx_story_dirty_marks_source` (`source_type`, `source_id`),
  KEY `idx_story_dirty_marks_source_chapter` (`source_chapter_id`),
  CONSTRAINT `fk_story_dirty_marks_project` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_story_dirty_marks_source_chapter` FOREIGN KEY (`source_chapter_id`) REFERENCES `chapters` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Downstream dirty ranges for story rebuild';
