CREATE TABLE `generation_batches` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `project_id` BIGINT UNSIGNED NOT NULL COMMENT '作品ID',
  `batch_type` VARCHAR(32) NOT NULL COMMENT '批次类型',
  `model_config_id` BIGINT UNSIGNED NULL COMMENT '模型配置ID',
  `status` VARCHAR(32) NOT NULL DEFAULT 'queued' COMMENT '批次状态',
  `total_count` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '总条目数',
  `pending_count` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '待执行数',
  `running_count` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '执行中数',
  `succeeded_count` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '成功数',
  `failed_count` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '失败数',
  `skipped_count` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '跳过数',
  `request_snapshot` JSON NOT NULL COMMENT '创建请求快照',
  `error_message` LONGTEXT NULL COMMENT '批次错误',
  `created_by` BIGINT UNSIGNED NULL COMMENT '创建用户ID',
  `started_at` DATETIME NULL COMMENT '开始时间',
  `finished_at` DATETIME NULL COMMENT '结束时间',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_generation_batches_project_status_created` (`project_id`, `status`, `created_at`),
  KEY `idx_generation_batches_model_config_id` (`model_config_id`),
  CONSTRAINT `fk_generation_batches_project` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_generation_batches_model_config` FOREIGN KEY (`model_config_id`) REFERENCES `model_configs` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='生成批次表';

CREATE TABLE `generation_batch_items` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `batch_id` BIGINT UNSIGNED NOT NULL COMMENT '批次ID',
  `project_id` BIGINT UNSIGNED NOT NULL COMMENT '作品ID',
  `chapter_id` BIGINT UNSIGNED NOT NULL COMMENT '章节ID',
  `chapter_no` INT UNSIGNED NOT NULL COMMENT '章节序号',
  `item_type` VARCHAR(32) NOT NULL COMMENT '条目类型',
  `status` VARCHAR(32) NOT NULL DEFAULT 'pending' COMMENT '条目状态',
  `attempt_count` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '执行次数',
  `generation_job_id` BIGINT UNSIGNED NULL COMMENT '生成任务ID',
  `error_message` LONGTEXT NULL COMMENT '执行错误',
  `started_at` DATETIME NULL COMMENT '开始时间',
  `finished_at` DATETIME NULL COMMENT '结束时间',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_generation_batch_items_batch_chapter` (`batch_id`, `chapter_id`),
  KEY `idx_generation_batch_items_batch_status_chapter` (`batch_id`, `status`, `chapter_no`),
  KEY `idx_generation_batch_items_project_status_chapter` (`project_id`, `status`, `chapter_no`),
  KEY `idx_generation_batch_items_generation_job_id` (`generation_job_id`),
  CONSTRAINT `fk_generation_batch_items_batch` FOREIGN KEY (`batch_id`) REFERENCES `generation_batches` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_generation_batch_items_project` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_generation_batch_items_chapter` FOREIGN KEY (`chapter_id`) REFERENCES `chapters` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_generation_batch_items_generation_job` FOREIGN KEY (`generation_job_id`) REFERENCES `generation_jobs` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='生成批次条目表';
