-- 第三版：章节记忆压缩系统
-- 说明：新增单章摘要与故事记忆快照，支撑近窗、中层、高层和全局总摘要；不修改已有表结构。

CREATE TABLE `chapter_summaries` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `project_id` BIGINT UNSIGNED NOT NULL COMMENT '作品ID',
  `chapter_id` BIGINT UNSIGNED NOT NULL COMMENT '章节ID',
  `chapter_no` INT UNSIGNED NOT NULL COMMENT '章节序号冗余，便于按章节范围组装上下文',
  `summary` LONGTEXT NOT NULL COMMENT '单章摘要',
  `key_events` JSON NULL COMMENT '关键事件列表',
  `character_changes` JSON NULL COMMENT '本章人物状态变化',
  `location_changes` JSON NULL COMMENT '本章地点移动或场景变化',
  `foreshadow_changes` JSON NULL COMMENT '本章伏笔新增、推进或回收记录',
  `source_content_version_id` BIGINT UNSIGNED NULL COMMENT '摘要对应的章节正文版本记录ID',
  `summary_version_id` BIGINT UNSIGNED NULL COMMENT '本次摘要生成对应的版本记录ID',
  `generation_job_id` BIGINT UNSIGNED NULL COMMENT '摘要生成任务ID',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_chapter_summaries_chapter` (`chapter_id`),
  KEY `idx_chapter_summaries_project_no` (`project_id`, `chapter_no`),
  KEY `idx_chapter_summaries_source_version` (`source_content_version_id`),
  KEY `idx_chapter_summaries_summary_version` (`summary_version_id`),
  KEY `idx_chapter_summaries_job_id` (`generation_job_id`),
  CONSTRAINT `fk_chapter_summaries_project` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_chapter_summaries_chapter` FOREIGN KEY (`chapter_id`) REFERENCES `chapters` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_chapter_summaries_source_version` FOREIGN KEY (`source_content_version_id`) REFERENCES `content_versions` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_chapter_summaries_summary_version` FOREIGN KEY (`summary_version_id`) REFERENCES `content_versions` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_chapter_summaries_job` FOREIGN KEY (`generation_job_id`) REFERENCES `generation_jobs` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='单章摘要表';

CREATE TABLE `story_memories` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键',
  `project_id` BIGINT UNSIGNED NOT NULL COMMENT '作品ID',
  `memory_type` VARCHAR(32) NOT NULL COMMENT '记忆层级：recent_window 近窗、middle 中层、high 高层、global 全局总摘要',
  `memory_key` VARCHAR(64) NOT NULL COMMENT '记忆标识，例如 window-1、middle-3、high-1、global',
  `sequence_no` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '同一作品同一层级下的顺序号',
  `start_chapter_no` INT UNSIGNED NULL COMMENT '覆盖起始章节序号',
  `end_chapter_no` INT UNSIGNED NULL COMMENT '覆盖结束章节序号',
  `content` LONGTEXT NOT NULL COMMENT '记忆摘要正文',
  `source_chapter_summary_ids` JSON NULL COMMENT '参与压缩的单章摘要ID列表',
  `source_memory_ids` JSON NULL COMMENT '参与压缩的下层记忆ID列表',
  `status` VARCHAR(32) NOT NULL DEFAULT 'active' COMMENT '状态：active 当前使用、compressed 已被上层压缩、superseded 已被新版本替换',
  `is_current` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否为当前上下文组装可用版本',
  `compression_round` INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '压缩轮次，0 表示直接生成，数值越大压缩层级越深',
  `generation_job_id` BIGINT UNSIGNED NULL COMMENT '记忆生成或压缩任务ID',
  `content_version_id` BIGINT UNSIGNED NULL COMMENT '本次记忆生成或压缩对应的版本记录ID',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_story_memories_project_type_current` (`project_id`, `memory_type`, `is_current`),
  KEY `idx_story_memories_project_range` (`project_id`, `start_chapter_no`, `end_chapter_no`),
  KEY `idx_story_memories_project_sequence` (`project_id`, `memory_type`, `sequence_no`),
  KEY `idx_story_memories_status` (`status`),
  KEY `idx_story_memories_job_id` (`generation_job_id`),
  KEY `idx_story_memories_version_id` (`content_version_id`),
  CONSTRAINT `fk_story_memories_project` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_story_memories_job` FOREIGN KEY (`generation_job_id`) REFERENCES `generation_jobs` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_story_memories_version` FOREIGN KEY (`content_version_id`) REFERENCES `content_versions` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='故事记忆快照表';
