CREATE TABLE `foreshadow_threads` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `project_id` BIGINT UNSIGNED NOT NULL,
  `thread_key` VARCHAR(128) NOT NULL,
  `thread_title` VARCHAR(255) NOT NULL,
  `thread_type` VARCHAR(32) NOT NULL DEFAULT 'foreshadow',
  `status` VARCHAR(16) NOT NULL DEFAULT 'active',
  `priority` INT NOT NULL DEFAULT 0,
  `source_chapter_id` BIGINT UNSIGNED NULL,
  `source_chapter_no` INT NULL,
  `last_mentioned_chapter_id` BIGINT UNSIGNED NULL,
  `last_mentioned_chapter_no` INT NULL,
  `target_payoff_chapter_no` INT NULL,
  `resolution_chapter_id` BIGINT UNSIGNED NULL,
  `resolution_chapter_no` INT NULL,
  `setup_text` LONGTEXT NULL,
  `latest_progress` LONGTEXT NULL,
  `payoff_hint` LONGTEXT NULL,
  `resolution_note` LONGTEXT NULL,
  `related_character_ids` JSON NULL,
  `related_organization_ids` JSON NULL,
  `related_location_ids` JSON NULL,
  `related_item_ids` JSON NULL,
  `notes` LONGTEXT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_foreshadow_threads_project_key` (`project_id`, `thread_key`),
  KEY `idx_foreshadow_threads_project_status` (`project_id`, `status`),
  KEY `idx_foreshadow_threads_project_type` (`project_id`, `thread_type`),
  KEY `idx_foreshadow_threads_project_priority` (`project_id`, `status`, `priority`, `last_mentioned_chapter_no`),
  KEY `idx_foreshadow_threads_source_chapter` (`source_chapter_id`),
  KEY `idx_foreshadow_threads_last_mentioned_chapter` (`last_mentioned_chapter_id`),
  KEY `idx_foreshadow_threads_resolution_chapter` (`resolution_chapter_id`),
  CONSTRAINT `fk_foreshadow_threads_project` FOREIGN KEY (`project_id`) REFERENCES `projects` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_foreshadow_threads_source_chapter` FOREIGN KEY (`source_chapter_id`) REFERENCES `chapters` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_foreshadow_threads_last_mentioned_chapter` FOREIGN KEY (`last_mentioned_chapter_id`) REFERENCES `chapters` (`id`) ON DELETE SET NULL,
  CONSTRAINT `fk_foreshadow_threads_resolution_chapter` FOREIGN KEY (`resolution_chapter_id`) REFERENCES `chapters` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Structured long-running story threads';
